-- H2 2.2.224; 
;              
CREATE USER IF NOT EXISTS "SA" SALT 'c33673d971a03019' HASH '9bb0dd1bc12b6270263f8e695cda814d07c738bdb91d5603827bf7521e905c50' ADMIN;          
CREATE CACHED TABLE "PUBLIC"."COST_ASSIGNMENTS"(
    "COST_ID" BIGINT NOT NULL,
    "EPIC_ID" BIGINT,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 9) NOT NULL,
    "WORK_ITEM_ID" BIGINT
);     
ALTER TABLE "PUBLIC"."COST_ASSIGNMENTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_54" PRIMARY KEY("ID");             
-- 8 +/- SELECT COUNT(*) FROM PUBLIC.COST_ASSIGNMENTS;         
INSERT INTO "PUBLIC"."COST_ASSIGNMENTS" VALUES
(1, 1, 1, NULL),
(2, 4, 2, NULL),
(3, 3, 3, NULL),
(4, 2, 4, NULL),
(5, 6, 5, NULL),
(6, NULL, 6, 22),
(7, NULL, 7, 35),
(8, 4, 8, NULL);       
CREATE CACHED TABLE "PUBLIC"."COSTS"(
    "AMOUNT" FLOAT(53),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 9) NOT NULL,
    "CATEGORY" CHARACTER VARYING(255),
    "DESCRIPTION" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255)
);    
ALTER TABLE "PUBLIC"."COSTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("ID");         
-- 8 +/- SELECT COUNT(*) FROM PUBLIC.COSTS;    
INSERT INTO "PUBLIC"."COSTS" VALUES
(5000.0, 1, 'Software', 'Software licenses and development tools', 'Development Tools'),
(2000.0, 2, 'Infrastructure', 'AWS cloud services', 'Cloud Infrastructure'),
(1000.0, 3, 'Software', 'Design software licenses', 'UI/UX Design Tools'),
(8000.0, 4, 'Services', 'Third-party security assessment', 'Security Audit'),
(3000.0, 5, 'Training', 'Team training and workshops', 'Training'),
(1500.0, 6, 'Software', 'QA and testing tools', 'Testing Tools'),
(4000.0, 7, 'Software', 'Database management system licenses', 'Database Licenses'),
(2500.0, 8, 'Infrastructure', 'Application monitoring and logging', 'Monitoring Tools');         
CREATE CACHED TABLE "PUBLIC"."EPICS"(
    "END_DATE" DATE,
    "START_DATE" DATE,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 8) NOT NULL,
    "PROJECT_ID" BIGINT,
    "DESCRIPTION" CHARACTER VARYING(255),
    "TITLE" CHARACTER VARYING(255)
);             
ALTER TABLE "PUBLIC"."EPICS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3F" PRIMARY KEY("ID");        
-- 7 +/- SELECT COUNT(*) FROM PUBLIC.EPICS;    
INSERT INTO "PUBLIC"."EPICS" VALUES
(DATE '2025-08-15', DATE '2025-06-15', 1, 1, 'User authentication, authorization, and profile management', 'User Management'),
(DATE '2025-09-15', DATE '2025-06-15', 2, 1, 'Product management, categories, and search functionality', 'Product Catalog'),
(DATE '2025-10-15', DATE '2025-07-15', 3, 1, 'Shopping cart management and secure checkout process', 'Shopping Cart & Checkout'),
(DATE '2025-09-15', DATE '2025-06-29', 4, 2, 'Secure authentication and encryption implementation', 'Security Infrastructure'),
(DATE '2025-10-15', DATE '2025-07-15', 5, 2, 'Account viewing, transactions, and transfers', 'Account Management'),
(DATE '2025-09-15', DATE '2025-06-15', 6, 3, 'Electronic health records management', 'Patient Records'),
(DATE '2025-10-15', DATE '2025-07-15', 7, 3, 'Appointment booking and management system', 'Appointment Scheduling');            
CREATE CACHED TABLE "PUBLIC"."PERSON_ASSIGNMENTS"(
    "HOURS" FLOAT(53),
    "EPIC_ID" BIGINT,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 48) NOT NULL,
    "PERSON_ID" BIGINT NOT NULL,
    "WORK_ITEM_ID" BIGINT,
    "DESCRIPTION" CHARACTER VARYING(255)
);               
ALTER TABLE "PUBLIC"."PERSON_ASSIGNMENTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B" PRIMARY KEY("ID");            
-- 47 +/- SELECT COUNT(*) FROM PUBLIC.PERSON_ASSIGNMENTS;      
INSERT INTO "PUBLIC"."PERSON_ASSIGNMENTS" VALUES
(52.39559643150037, 2, 1, 1, NULL, 'Working on Product Catalog'),
(22.28073321517771, NULL, 2, 1, 44, 'Assigned to Analytics Dashboard'),
(23.124240937016562, NULL, 3, 1, 17, 'Assigned to Performance Monitoring Setup'),
(11.864790702851204, NULL, 4, 1, 1, 'Assigned to Setup Development Environment'),
(10.681418442172339, NULL, 5, 1, 4, 'Assigned to User Authentication Flow'),
(53.064371694445526, 1, 6, 2, NULL, 'Working on User Management'),
(50.611170654679455, 2, 7, 2, NULL, 'Working on Product Catalog'),
(23.97110709602469, NULL, 8, 2, 36, 'Assigned to Mobile Responsive Design'),
(28.86919473033167, NULL, 9, 2, 23, 'Assigned to Performance Monitoring Setup'),
(19.182772685262446, NULL, 10, 2, 22, 'Assigned to User Authentication Flow'),
(19.181513356098858, NULL, 11, 2, 26, 'Assigned to Mobile Responsive Design'),
(26.622321797136536, 4, 12, 3, NULL, 'Working on Security Infrastructure'),
(24.891906330701566, NULL, 13, 3, 19, 'Assigned to Setup Development Environment'),
(25.325346888446134, NULL, 14, 3, 20, 'Assigned to Design Database Schema'),
(29.84122527744953, 3, 15, 4, NULL, 'Working on Shopping Cart & Checkout'),
(46.035665595834914, 4, 16, 4, NULL, 'Working on Security Infrastructure'),
(28.26466712892971, NULL, 17, 4, 41, 'Assigned to Mobile Responsive Design'),
(17.634880551101336, NULL, 18, 4, 31, 'Assigned to Mobile Responsive Design'),
(14.344167545055901, NULL, 19, 4, 6, 'Assigned to Security Vulnerability Scan'),
(24.661932225595994, 1, 20, 5, NULL, 'Working on User Management'),
(10.079380193999834, NULL, 21, 5, 1, 'Assigned to Setup Development Environment'),
(29.445238737742976, NULL, 22, 5, 27, 'Assigned to Payment Integration'),
(11.634470613850045, NULL, 23, 5, 32, 'Assigned to Payment Integration'),
(14.950876047099161, NULL, 24, 5, 15, 'Assigned to API Documentation'),
(28.50311321498905, 7, 25, 6, NULL, 'Working on Appointment Scheduling'),
(13.72685678008665, NULL, 26, 6, 25, 'Assigned to Implement Caching Layer'),
(21.89260102590619, NULL, 27, 6, 31, 'Assigned to Mobile Responsive Design'),
(25.822893903462557, NULL, 28, 6, 38, 'Assigned to Search Optimization'),
(43.46488586212251, 3, 29, 7, NULL, 'Working on Shopping Cart & Checkout'),
(29.319288248585355, NULL, 30, 7, 11, 'Assigned to Performance Monitoring Setup'),
(28.226173272465253, NULL, 31, 7, 36, 'Assigned to Mobile Responsive Design'),
(25.217341039411053, NULL, 32, 7, 41, 'Assigned to Mobile Responsive Design'),
(12.350944049495974, NULL, 33, 7, 5, 'Assigned to Performance Monitoring Setup'),
(42.36249571724743, 2, 34, 8, NULL, 'Working on Product Catalog'),
(51.15962909492285, 2, 35, 8, NULL, 'Working on Product Catalog'),
(11.084869417279123, NULL, 36, 8, 34, 'Assigned to Analytics Dashboard'),
(11.356788486879823, NULL, 37, 8, 20, 'Assigned to Design Database Schema'),
(19.580342592961717, NULL, 38, 8, 33, 'Assigned to Search Optimization'),
(24.514858307981015, NULL, 39, 8, 12, 'Assigned to Security Vulnerability Scan'),
(31.378739773167084, 2, 40, 9, NULL, 'Working on Product Catalog'),
(26.848093371314125, NULL, 41, 9, 33, 'Assigned to Search Optimization'),
(12.402364241022571, NULL, 42, 9, 44, 'Assigned to Analytics Dashboard'),
(51.764129250749384, 1, 43, 10, NULL, 'Working on User Management'),
(54.18186261936225, 2, 44, 10, NULL, 'Working on Product Catalog'),
(20.17368353674092, NULL, 45, 10, 11, 'Assigned to Performance Monitoring Setup'),
(17.10301762807916, NULL, 46, 10, 2, 'Assigned to Design Database Schema'),
(17.956047130276886, NULL, 47, 10, 8, 'Assigned to Design Database Schema');        
CREATE CACHED TABLE "PUBLIC"."PERSONS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 11) NOT NULL,
    "EMAIL" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "ROLE" CHARACTER VARYING(255)
);   
ALTER TABLE "PUBLIC"."PERSONS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");       
-- 10 +/- SELECT COUNT(*) FROM PUBLIC.PERSONS; 
INSERT INTO "PUBLIC"."PERSONS" VALUES
(1, 'john.doe@example.com', 'John Doe', 'Developer'),
(2, 'jane.smith@example.com', 'Jane Smith', 'Designer'),
(3, 'bob.johnson@example.com', 'Bob Johnson', 'Product Owner'),
(4, 'alice.brown@example.com', 'Alice Brown', 'Scrum Master'),
(5, 'charlie.wilson@example.com', 'Charlie Wilson', 'Tester'),
(6, 'david.lee@example.com', 'David Lee', 'DevOps Engineer'),
(7, 'emma.davis@example.com', 'Emma Davis', 'Business Analyst'),
(8, 'frank.miller@example.com', 'Frank Miller', 'Technical Lead'),
(9, 'grace.taylor@example.com', 'Grace Taylor', 'UX Researcher'),
(10, 'henry.wilson@example.com', 'Henry Wilson', 'QA Lead');            
CREATE CACHED TABLE "PUBLIC"."PROJECTS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 5) NOT NULL,
    "DESCRIPTION" CHARACTER VARYING(255),
    "STATUS" CHARACTER VARYING(255),
    "TITLE" CHARACTER VARYING(255) NOT NULL
); 
ALTER TABLE "PUBLIC"."PROJECTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F3" PRIMARY KEY("ID");     
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.PROJECTS; 
INSERT INTO "PUBLIC"."PROJECTS" VALUES
(1, 'Online shopping platform with modern UI and advanced features', 'ACTIVE', 'E-Commerce Platform'),
(2, 'Secure mobile banking application with biometric authentication', 'PLANNING', 'Mobile Banking App'),
(3, 'Integrated healthcare management solution for hospitals', 'ACTIVE', 'Healthcare Management System'),
(4, 'IoT platform for smart home device management', 'PLANNING', 'Smart Home IoT Platform'); 
CREATE CACHED TABLE "PUBLIC"."SPRINTS"(
    "END_DATE" DATE,
    "START_DATE" DATE,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 17) NOT NULL,
    "PROJECT_ID" BIGINT,
    "GOAL" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "STATUS" CHARACTER VARYING(255)
);             
ALTER TABLE "PUBLIC"."SPRINTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B3C" PRIMARY KEY("ID");     
-- 16 +/- SELECT COUNT(*) FROM PUBLIC.SPRINTS; 
INSERT INTO "PUBLIC"."SPRINTS" VALUES
(DATE '2025-06-01', DATE '2025-05-18', 1, 1, 'Project setup and infrastructure', 'Sprint 1', 'ACTIVE'),
(DATE '2025-06-29', DATE '2025-06-15', 2, 1, 'Core features implementation', 'Sprint 2', 'ACTIVE'),
(DATE '2025-07-13', DATE '2025-06-29', 3, 1, 'Advanced features and integrations', 'Sprint 3', 'NOT_STARTED'),
(DATE '2025-07-27', DATE '2025-07-13', 4, 1, 'Performance optimization and security', 'Sprint 4', 'NOT_STARTED'),
(DATE '2025-06-01', DATE '2025-05-18', 5, 2, 'Project setup and infrastructure', 'Sprint 1', 'ACTIVE'),
(DATE '2025-06-29', DATE '2025-06-15', 6, 2, 'Core features implementation', 'Sprint 2', 'ACTIVE'),
(DATE '2025-07-13', DATE '2025-06-29', 7, 2, 'Advanced features and integrations', 'Sprint 3', 'NOT_STARTED'),
(DATE '2025-07-27', DATE '2025-07-13', 8, 2, 'Performance optimization and security', 'Sprint 4', 'NOT_STARTED'),
(DATE '2025-06-01', DATE '2025-05-18', 9, 3, 'Project setup and infrastructure', 'Sprint 1', 'ACTIVE'),
(DATE '2025-06-29', DATE '2025-06-15', 10, 3, 'Core features implementation', 'Sprint 2', 'ACTIVE'),
(DATE '2025-07-13', DATE '2025-06-29', 11, 3, 'Advanced features and integrations', 'Sprint 3', 'NOT_STARTED'),
(DATE '2025-07-27', DATE '2025-07-13', 12, 3, 'Performance optimization and security', 'Sprint 4', 'NOT_STARTED'),
(DATE '2025-06-01', DATE '2025-05-18', 13, 4, 'Project setup and infrastructure', 'Sprint 1', 'ACTIVE'),
(DATE '2025-06-29', DATE '2025-06-15', 14, 4, 'Core features implementation', 'Sprint 2', 'ACTIVE'),
(DATE '2025-07-13', DATE '2025-06-29', 15, 4, 'Advanced features and integrations', 'Sprint 3', 'NOT_STARTED'),
(DATE '2025-07-27', DATE '2025-07-13', 16, 4, 'Performance optimization and security', 'Sprint 4', 'NOT_STARTED');               
CREATE CACHED TABLE "PUBLIC"."WORK_ITEMS"(
    "STORY_POINTS" INTEGER,
    "EPIC_ID" BIGINT,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 45) NOT NULL,
    "PROJECT_ID" BIGINT,
    "SPRINT_ID" BIGINT,
    "DESCRIPTION" CHARACTER VARYING(255),
    "LOCATION" CHARACTER VARYING(255),
    "PRIORITY" CHARACTER VARYING(255),
    "STATUS" CHARACTER VARYING(255),
    "TITLE" CHARACTER VARYING(255),
    "TYPE" CHARACTER VARYING(255)
);   
ALTER TABLE "PUBLIC"."WORK_ITEMS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_31EFC0" PRIMARY KEY("ID");               
-- 44 +/- SELECT COUNT(*) FROM PUBLIC.WORK_ITEMS;              
INSERT INTO "PUBLIC"."WORK_ITEMS" VALUES
(3, NULL, 1, 1, NULL, 'Configure development tools and environments', 'BACKLOG', 'HIGH', 'DONE', 'Setup Development Environment', 'TASK'),
(5, NULL, 2, 1, NULL, 'Create initial database design', 'BACKLOG', 'HIGH', 'IN_PROGRESS', 'Design Database Schema', 'TASK'),
(3, NULL, 3, 1, NULL, 'Create API documentation using Swagger', 'BACKLOG', 'MEDIUM', 'TODO', 'API Documentation', 'TASK'),
(8, 2, 4, 1, 1, 'Implement secure user authentication', 'SPRINT', 'HIGH', 'IN_PROGRESS', 'User Authentication Flow', 'STORY'),
(5, NULL, 5, 1, 1, 'Set up application performance monitoring', 'SPRINT', 'MEDIUM', 'TODO', 'Performance Monitoring Setup', 'TASK'),
(3, NULL, 6, 1, 2, 'Perform security assessment', 'SPRINT', 'HIGH', 'TODO', 'Security Vulnerability Scan', 'BUG'),
(3, NULL, 7, 2, NULL, 'Configure development tools and environments', 'BACKLOG', 'HIGH', 'DONE', 'Setup Development Environment', 'TASK'),
(5, NULL, 8, 2, NULL, 'Create initial database design', 'BACKLOG', 'HIGH', 'IN_PROGRESS', 'Design Database Schema', 'TASK'),
(3, NULL, 9, 2, NULL, 'Create API documentation using Swagger', 'BACKLOG', 'MEDIUM', 'TODO', 'API Documentation', 'TASK'),
(8, NULL, 10, 2, 5, 'Implement secure user authentication', 'SPRINT', 'HIGH', 'IN_PROGRESS', 'User Authentication Flow', 'STORY'),
(5, NULL, 11, 2, 5, 'Set up application performance monitoring', 'SPRINT', 'MEDIUM', 'TODO', 'Performance Monitoring Setup', 'TASK'),
(3, NULL, 12, 2, 6, 'Perform security assessment', 'SPRINT', 'HIGH', 'TODO', 'Security Vulnerability Scan', 'BUG'),
(3, NULL, 13, 3, NULL, 'Configure development tools and environments', 'BACKLOG', 'HIGH', 'DONE', 'Setup Development Environment', 'TASK'),
(5, NULL, 14, 3, NULL, 'Create initial database design', 'BACKLOG', 'HIGH', 'IN_PROGRESS', 'Design Database Schema', 'TASK'),
(3, 6, 15, 3, NULL, 'Create API documentation using Swagger', 'BACKLOG', 'MEDIUM', 'TODO', 'API Documentation', 'TASK'),
(8, NULL, 16, 3, 9, 'Implement secure user authentication', 'SPRINT', 'HIGH', 'IN_PROGRESS', 'User Authentication Flow', 'STORY'),
(5, NULL, 17, 3, 9, 'Set up application performance monitoring', 'SPRINT', 'MEDIUM', 'TODO', 'Performance Monitoring Setup', 'TASK'),
(3, NULL, 18, 3, 10, 'Perform security assessment', 'SPRINT', 'HIGH', 'TODO', 'Security Vulnerability Scan', 'BUG'),
(3, NULL, 19, 4, NULL, 'Configure development tools and environments', 'BACKLOG', 'HIGH', 'DONE', 'Setup Development Environment', 'TASK'),
(5, NULL, 20, 4, NULL, 'Create initial database design', 'BACKLOG', 'HIGH', 'IN_PROGRESS', 'Design Database Schema', 'TASK'),
(3, NULL, 21, 4, NULL, 'Create API documentation using Swagger', 'BACKLOG', 'MEDIUM', 'TODO', 'API Documentation', 'TASK'),
(8, NULL, 22, 4, 13, 'Implement secure user authentication', 'SPRINT', 'HIGH', 'IN_PROGRESS', 'User Authentication Flow', 'STORY'),
(5, NULL, 23, 4, 13, 'Set up application performance monitoring', 'SPRINT', 'MEDIUM', 'TODO', 'Performance Monitoring Setup', 'TASK'),
(3, NULL, 24, 4, 14, 'Perform security assessment', 'SPRINT', 'HIGH', 'TODO', 'Security Vulnerability Scan', 'BUG'),
(5, 3, 25, 1, NULL, 'Add Redis caching for improved performance', 'BACKLOG', 'HIGH', 'TODO', 'Implement Caching Layer', 'TASK'),
(8, 3, 26, 1, NULL, 'Ensure UI works well on mobile devices', 'BACKLOG', 'MEDIUM', 'TODO', 'Mobile Responsive Design', 'STORY'),
(13, NULL, 27, 1, 2, 'Integrate with payment gateway', 'SPRINT', 'HIGH', 'TODO', 'Payment Integration', 'STORY'),
(5, NULL, 28, 1, 3, 'Improve search performance and accuracy', 'SPRINT', 'MEDIUM', 'TODO', 'Search Optimization', 'TASK'),
(8, 2, 29, 1, NULL, 'Create analytics dashboard for admins', 'BACKLOG', 'LOW', 'TODO', 'Analytics Dashboard', 'STORY'),
(5, 4, 30, 2, NULL, 'Add Redis caching for improved performance', 'BACKLOG', 'HIGH', 'TODO', 'Implement Caching Layer', 'TASK'),
(8, NULL, 31, 2, NULL, 'Ensure UI works well on mobile devices', 'BACKLOG', 'MEDIUM', 'TODO', 'Mobile Responsive Design', 'STORY'),
(13, 4, 32, 2, 6, 'Integrate with payment gateway', 'SPRINT', 'HIGH', 'TODO', 'Payment Integration', 'STORY');           
INSERT INTO "PUBLIC"."WORK_ITEMS" VALUES
(5, 4, 33, 2, 7, 'Improve search performance and accuracy', 'SPRINT', 'MEDIUM', 'TODO', 'Search Optimization', 'TASK'),
(8, 4, 34, 2, NULL, 'Create analytics dashboard for admins', 'BACKLOG', 'LOW', 'TODO', 'Analytics Dashboard', 'STORY'),
(5, 6, 35, 3, NULL, 'Add Redis caching for improved performance', 'BACKLOG', 'HIGH', 'TODO', 'Implement Caching Layer', 'TASK'),
(8, NULL, 36, 3, NULL, 'Ensure UI works well on mobile devices', 'BACKLOG', 'MEDIUM', 'TODO', 'Mobile Responsive Design', 'STORY'),
(13, NULL, 37, 3, 10, 'Integrate with payment gateway', 'SPRINT', 'HIGH', 'TODO', 'Payment Integration', 'STORY'),
(5, NULL, 38, 3, 11, 'Improve search performance and accuracy', 'SPRINT', 'MEDIUM', 'TODO', 'Search Optimization', 'TASK'),
(8, 6, 39, 3, NULL, 'Create analytics dashboard for admins', 'BACKLOG', 'LOW', 'TODO', 'Analytics Dashboard', 'STORY'),
(5, NULL, 40, 4, NULL, 'Add Redis caching for improved performance', 'BACKLOG', 'HIGH', 'TODO', 'Implement Caching Layer', 'TASK'),
(8, NULL, 41, 4, NULL, 'Ensure UI works well on mobile devices', 'BACKLOG', 'MEDIUM', 'TODO', 'Mobile Responsive Design', 'STORY'),
(13, NULL, 42, 4, 14, 'Integrate with payment gateway', 'SPRINT', 'HIGH', 'TODO', 'Payment Integration', 'STORY'),
(5, NULL, 43, 4, 15, 'Improve search performance and accuracy', 'SPRINT', 'MEDIUM', 'TODO', 'Search Optimization', 'TASK'),
(8, NULL, 44, 4, NULL, 'Create analytics dashboard for admins', 'BACKLOG', 'LOW', 'TODO', 'Analytics Dashboard', 'STORY');         
ALTER TABLE "PUBLIC"."WORK_ITEMS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_31EFC" CHECK("TYPE" IN('TASK', 'STORY', 'BUG')) NOCHECK; 
ALTER TABLE "PUBLIC"."WORK_ITEMS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_31" CHECK("LOCATION" IN('BACKLOG', 'SPRINT', 'COMPLETED')) NOCHECK;      
ALTER TABLE "PUBLIC"."WORK_ITEMS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_31EF" CHECK("STATUS" IN('TODO', 'IN_PROGRESS', 'DONE')) NOCHECK;         
ALTER TABLE "PUBLIC"."SPRINTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B3" CHECK("STATUS" IN('NOT_STARTED', 'ACTIVE', 'COMPLETED')) NOCHECK;       
ALTER TABLE "PUBLIC"."WORK_ITEMS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_31E" CHECK("PRIORITY" IN('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')) NOCHECK;  
ALTER TABLE "PUBLIC"."PROJECTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" CHECK("STATUS" IN('PLANNING', 'ACTIVE', 'ARCHIVED')) NOCHECK;           
ALTER TABLE "PUBLIC"."COST_ASSIGNMENTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5" UNIQUE("COST_ID");              
ALTER TABLE "PUBLIC"."PROJECTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F31" UNIQUE("TITLE");      
ALTER TABLE "PUBLIC"."EPICS" ADD CONSTRAINT "PUBLIC"."FK2HDAESLVDK335BHP32FAD99U7" FOREIGN KEY("PROJECT_ID") REFERENCES "PUBLIC"."PROJECTS"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."SPRINTS" ADD CONSTRAINT "PUBLIC"."FKKE5A9E380IBC0XUGYKEQAKTP4" FOREIGN KEY("PROJECT_ID") REFERENCES "PUBLIC"."PROJECTS"("ID") NOCHECK;   
ALTER TABLE "PUBLIC"."WORK_ITEMS" ADD CONSTRAINT "PUBLIC"."FKAPYWI3WWQQ6B4IPPDQM6292LD" FOREIGN KEY("SPRINT_ID") REFERENCES "PUBLIC"."SPRINTS"("ID") NOCHECK;  
ALTER TABLE "PUBLIC"."WORK_ITEMS" ADD CONSTRAINT "PUBLIC"."FKMD40FN5HUXMCRVP3F04VI5CRL" FOREIGN KEY("EPIC_ID") REFERENCES "PUBLIC"."EPICS"("ID") NOCHECK;      
ALTER TABLE "PUBLIC"."WORK_ITEMS" ADD CONSTRAINT "PUBLIC"."FKC9HQ5IFP15UVQOCYXT1I6S9W2" FOREIGN KEY("PROJECT_ID") REFERENCES "PUBLIC"."PROJECTS"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."COST_ASSIGNMENTS" ADD CONSTRAINT "PUBLIC"."FKGOF9YRL8KVUKX50E9MQTE5QN" FOREIGN KEY("WORK_ITEM_ID") REFERENCES "PUBLIC"."WORK_ITEMS"("ID") NOCHECK;       
ALTER TABLE "PUBLIC"."PERSON_ASSIGNMENTS" ADD CONSTRAINT "PUBLIC"."FKG47Q5MPWQ1SVUOEKPPDY7XD3T" FOREIGN KEY("EPIC_ID") REFERENCES "PUBLIC"."EPICS"("ID") NOCHECK;              
ALTER TABLE "PUBLIC"."PERSON_ASSIGNMENTS" ADD CONSTRAINT "PUBLIC"."FKJK5A4QNVI798UN1RW9S1645RG" FOREIGN KEY("PERSON_ID") REFERENCES "PUBLIC"."PERSONS"("ID") NOCHECK;          
ALTER TABLE "PUBLIC"."COST_ASSIGNMENTS" ADD CONSTRAINT "PUBLIC"."FKNCU3K114AX4TGUN8NY5HEF3Y0" FOREIGN KEY("EPIC_ID") REFERENCES "PUBLIC"."EPICS"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."PERSON_ASSIGNMENTS" ADD CONSTRAINT "PUBLIC"."FKI56ARW4S2ARINKPF0A5G276U3" FOREIGN KEY("WORK_ITEM_ID") REFERENCES "PUBLIC"."WORK_ITEMS"("ID") NOCHECK;    
ALTER TABLE "PUBLIC"."COST_ASSIGNMENTS" ADD CONSTRAINT "PUBLIC"."FKPRP7LHV673SOMMGB9OL11LLH8" FOREIGN KEY("COST_ID") REFERENCES "PUBLIC"."COSTS"("ID") NOCHECK;
